# Generated by Django 5.2.4 on 2025-07-25 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoExtraido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_producto', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('color', models.CharField(max_length=50)),
                ('stock_local', models.IntegerField()),
                ('stock_general', models.IntegerField()),
                ('deposito1', models.IntegerField()),
                ('deposito2', models.IntegerField()),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
