# Generated by Django 5.2.4 on 2025-07-26 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Extractor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productoextraido',
            old_name='stock_local',
            new_name='unidades_vendidas',
        ),
    ]
