# Generated by Django 5.2.4 on 2025-07-26 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Extractor', '0002_rename_stock_local_productoextraido_unidades_vendidas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoextraido',
            name='unidades_vendidas',
            field=models.IntegerField(default=0),
        ),
    ]
