# Generated by Django 5.2.4 on 2025-07-26 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Extractor', '0003_alter_productoextraido_unidades_vendidas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoextraido',
            name='color',
            field=models.CharField(default='VARIOS', max_length=50),
        ),
        migrations.AlterField(
            model_name='productoextraido',
            name='deposito1',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='productoextraido',
            name='deposito2',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='productoextraido',
            name='stock_general',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterModelTable(
            name='productoextraido',
            table='productos_extraidos',
        ),
    ]
