# Generated by Django 5.2.4 on 2025-07-26 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Extractor', '0004_alter_productoextraido_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoextraido',
            name='talle',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
