# Generated by Django 5.2.4 on 2025-07-26 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Extractor', '0005_productoextraido_talle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoextraido',
            name='talle',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
