[project]
name = "src"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "django>=5.2.4",
    "dotenv>=0.9.9",
    "extractor>=0.5",
    "mysqlclient>=2.2.7",
    "pdfplumber>=0.11.7",
    "pymysql>=1.1.1",
]
